package com.nihalsoft.java.jdbc.orm.annotation;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

@Retention(RUNTIME)
@Target({ METHOD })
public @interface Column {

    String name() default "";

    boolean autoGeneratedId() default false;
    
    boolean persist() default true;

}
