package com.nihalsoft.java.jdbc.orm.common;

import com.nihalsoft.java.jdbc.orm.annotation.Column;

public class ColumnInfo {

    private String name = "";
    private Object value = null;
    private Column meta;

    public ColumnInfo(String name, Object value, Column meta) {
        this.name = name;
        this.value = value;
        this.meta = meta;
    }

    public String getName() {
        return name;
    }

    public Object getValue() {
        return value;
    }

    public boolean hasValue() {
        return value != null;
    }

    public Column getMeta() {
        return meta;
    }

    public boolean persist() {
        if (meta.autoGeneratedId()) {
            return false;
        }
        return meta.persist();
    }
}
